spring:
  application:
    name: spring-boot-querydsl-sample
  datasource:
    url: jdbc:h2:mem:testdb
    username: naruto
    password: naruto
  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
